import type { Card, CardCategory, CardColor } from './types.js';

// ============================================================
// 72 张测试卡
// 互动牌 24 / 守护牌 14 / 活力牌 8 / 奇遇牌 10 / 道具牌 8 / 友情牌 8
// 所有卡牌使用原创名称、图标方向和文字
// ============================================================

const c = (
  id: string,
  name: string,
  category: CardCategory,
  color: CardColor,
  description: string,
  hint: string,
  effects: Card['effects'],
  rarity: Card['rarity'] = 'common'
): Card => ({ id, name, category, color, description, hint, effects, rarity });

export const CARDS: Card[] = [
  // ==================== 互动牌 24 张 ====================
  c('I01', '活力泡泡', 'interact', 'coralPink',
    '对一名玩家造成 1 点活力伤害。', '选择一个目标，让它失去 1 点活力。',
    [{ type: 'damage', value: 1, target: 'other' }]),
  c('I02', '换座位', 'interact', 'tideCyan',
    '交换两名玩家的行动顺序。', '选择两名玩家，交换他们在行动序列中的位置。',
    [{ type: 'reorderTurn', target: 'any' }]),
  c('I03', '偷看一眼', 'interact', 'starBlue',
    '秘密查看一名玩家的一张随机手牌。', '只有你能看到这张牌，不要声张哦。',
    [{ type: 'peekHand', target: 'other' }]),
  c('I04', '交换手牌', 'interact', 'coralPink',
    '与一名玩家各选一张手牌进行交换。', '你和目标各选 1 张牌，同时交换。',
    [{ type: 'swapCard', target: 'other' }]),
  c('I05', '复制技能', 'interact', 'mistPurple',
    '临时复制一名玩家已公开的角色技能，本轮可使用一次。', '选择一名玩家，复制其技能效果。',
    [{ type: 'copySkill', target: 'other' }]),
  c('I06', '禁止互动', 'interact', 'mossGreen',
    '本轮禁止所有玩家使用某一类别的卡牌。', '选择一个卡牌类别，本轮无人能打出该类牌。',
    [{ type: 'banCategory', target: 'all' }]),
  c('I07', '秘密帮助', 'interact', 'mistPurple',
    '秘密选择：帮助目标（+1 友情）或捣蛋目标（-1 活力）。', '你的选择只有自己知道，结果会匿名显示。',
    [{ type: 'secretAid', target: 'other' }], 'variable'),
  c('I08', '转移霉运', 'interact', 'coralPink',
    '将你身上的一个负面效果转移给一名玩家。', '把坏运气送给别人吧（但可能影响友情）。',
    [{ type: 'transferNegative', target: 'other' }]),
  c('I09', '友情测试', 'interact', 'coralPink',
    '若与目标友情达到 3，双方各 +1 友情；否则目标失去 1 活力。', '考验你们友情的时刻到了！',
    [{ type: 'damage', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'other' }], 'variable'),
  c('I10', '打乱顺序', 'interact', 'tideCyan',
    '重新随机排列所有玩家的行动顺序。', '下一轮谁先行动？全看运气！',
    [{ type: 'reorderTurn', target: 'all' }]),
  c('I11', '偷换概念', 'interact', 'mistPurple',
    '将一张已打出的互动牌的目标重定向到另一名玩家。', '在别人出牌时使用，改变它的目标。',
    [{ type: 'modifyScene', target: 'any' }], 'variable'),
  c('I12', '真心话', 'interact', 'starBlue',
    '目标必须向全队公开一张手牌。', '说真话！让大家看看你手里有什么。',
    [{ type: 'peekHand', target: 'other' }]),
  c('I13', '大冒险', 'interact', 'coralPink',
    '目标选择：弃 1 张牌，或失去 1 点活力。', '选一个吧，都不太好受。',
    [{ type: 'discard', value: 1, target: 'other' }, { type: 'damage', value: 1, target: 'other' }], 'variable'),
  c('I14', '交换线索', 'interact', 'starBlue',
    '你和目标各秘密查看对方一张手牌。', '互相交换情报，但不要让别人知道。',
    [{ type: 'peekHand', target: 'other' }]),
  c('I15', '恶作剧', 'interact', 'coralPink',
    '目标下回合不能使用角色技能。', '给目标的技能"上锁"一回合。',
    [{ type: 'banCategory', target: 'other' }]),
  c('I16', '联手出击', 'interact', 'coralPink',
    '你和另一名玩家协作，对目标造成 1 点伤害，协作者 +1 友情。', '找一个帮手一起行动！',
    [{ type: 'damage', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'self' }]),
  c('I17', '抢话', 'interact', 'tideCyan',
    '你获得下回合的优先行动权。', '插队！下一轮你第一个行动。',
    [{ type: 'reorderTurn', target: 'self' }]),
  c('I18', '传话筒', 'interact', 'coralPink',
    '秘密告知目标一条信息，双方各 +1 友情。', '说句悄悄话，拉近关系。',
    [{ type: 'gainFriendship', value: 1, target: 'other' }]),
  c('I19', '公平对决', 'interact', 'coralPink',
    '你和目标各弃 1 张牌，随机一方让对方失去 1 活力。', '纯靠运气的对决！',
    [{ type: 'randomEvent', target: 'other' }], 'variable'),
  c('I20', '临时结盟', 'interact', 'coralPink',
    '与一名玩家建立临时羁绊。', '你们成为临时伙伴，共享部分优势。',
    [{ type: 'formBond', target: 'other' }]),
  c('I21', '拆台', 'interact', 'coralPink',
    '解除一名玩家的一条羁绊。', '拆散一对临时伙伴。',
    [{ type: 'breakBond', target: 'other' }]),
  c('I22', '烟雾弹', 'interact', 'mistPurple',
    '目标本轮的行动类型对其他玩家隐藏。', '让目标的行动变成"神秘行动"。',
    [{ type: 'modifyScene', target: 'other' }]),
  c('I23', '反向操作', 'interact', 'mistPurple',
    '将目标的下一次正面效果转为负面效果。', '反转！好事变坏事。',
    [{ type: 'modifyScene', target: 'other' }], 'rare'),
  c('I24', '心愿干扰', 'interact', 'coralPink',
    '团队心愿进度 -1（最低为 0）。', '破坏大心愿星的修复进程。',
    [{ type: 'modifyScene', target: 'all' }], 'rare'),

  // ==================== 守护牌 14 张 ====================
  c('G01', '软绵护垫', 'guard', 'mossGreen',
    '获得 2 层护盾，每层抵消 1 点伤害。', '护盾会在受到伤害时自动消耗。',
    [{ type: 'shield', value: 2, target: 'self' }]),
  c('G02', '坚果头盔', 'guard', 'mossGreen',
    '免疫一次"弃牌"效果。', '下次有人让你弃牌时，直接无视。',
    [{ type: 'shield', value: 1, target: 'self' }]),
  c('G03', '泡泡雨衣', 'guard', 'tideCyan',
    '本轮免疫场景牌造成的负面效果。', '穿上雨衣，不怕场景搞事。',
    [{ type: 'shield', value: 1, target: 'self' }]),
  c('G04', '树叶盾牌', 'guard', 'mossGreen',
    '替一名队友承受下一次 1 点伤害，你 +1 友情。', '站在朋友前面！',
    [{ type: 'transferNegative', target: 'self' }, { type: 'gainFriendship', value: 1, target: 'self' }]),
  c('G05', '安静铃铛', 'guard', 'mossGreen',
    '取消一次全体强制效果（如全员弃牌）。', '摇一摇铃铛，让大家安静下来。',
    [{ type: 'modifyScene', target: 'all' }]),
  c('G06', '备用翅膀', 'guard', 'tideCyan',
    '被迫移动或弃牌时，改为摸 1 张牌。', '化险为夷，还能多摸一张。',
    [{ type: 'draw', value: 1, target: 'self' }]),
  c('G07', '糖霜绷带', 'guard', 'honeyYellow',
    '恢复 2 点活力，但下回合不能使用攻击类互动牌。', '治疗有代价，下回合只能防守。',
    [{ type: 'heal', value: 2, target: 'self' }, { type: 'banCategory', target: 'self' }]),
  c('G08', '夜灯结界', 'guard', 'mistPurple',
    '直到你下回合开始，其他玩家不能成为场景的直接目标。', '点亮夜灯，保护所有人。',
    [{ type: 'shield', value: 1, target: 'all' }]),
  c('G09', '回声耳罩', 'guard', 'starBlue',
    '取消一次"公开手牌"效果。', '戴上耳罩，别人看不到你的牌。',
    [{ type: 'modifyScene', target: 'self' }]),
  c('G10', '雾壳', 'guard', 'mistPurple',
    '将一次失败效果转化为部分成功（伤害减半、效果减弱）。', '在雾中，坏事也没那么坏。',
    [{ type: 'failureToReward', target: 'self' }], 'variable'),
  c('G11', '潮汐浮标', 'guard', 'tideCyan',
    '当你将进入梦境旁观者时，保留 1 点活力并摸 1 张牌。每局一次。', '救命浮标！每局限用一次。',
    [{ type: 'heal', value: 1, target: 'self' }, { type: 'draw', value: 1, target: 'self' }], 'rare'),
  c('G12', '修补针线', 'guard', 'mossGreen',
    '移除一名玩家的一个负面状态，并令其 +1 友情。', '缝缝补补，坏状态都走开。',
    [{ type: 'heal', value: 0, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'other' }]),
  c('G13', '背靠背', 'guard', 'mossGreen',
    '你和一名玩家各自获得 1 层护盾，直到下回合开始。', '背靠背，一起防守！',
    [{ type: 'shield', value: 1, target: 'other' }, { type: 'shield', value: 1, target: 'self' }]),
  c('G14', '守护誓言', 'guard', 'mossGreen',
    '与一名玩家建立羁绊，羁绊存在期间双方各 +1 护盾。', '立下誓言，互相守护。',
    [{ type: 'formBond', target: 'other' }, { type: 'shield', value: 1, target: 'other' }], 'rare'),

  // ==================== 活力牌 8 张 ====================
  c('V01', '活力果汁', 'vitality', 'honeyYellow',
    '恢复 1 点活力。', '喝一口，精神满满。',
    [{ type: 'heal', value: 1, target: 'self' }]),
  c('V02', '能量糖果', 'vitality', 'honeyYellow',
    '恢复 2 点活力。', '高能量糖果，快速回血。',
    [{ type: 'heal', value: 2, target: 'self' }]),
  c('V03', '元气早餐', 'vitality', 'honeyYellow',
    '全队各恢复 1 点活力。', '一起吃早餐，大家都元气满满！',
    [{ type: 'heal', value: 1, target: 'all' }]),
  c('V04', '急救包', 'vitality', 'honeyYellow',
    '救回一名梦境旁观者，使其恢复至 1 点活力。', '把睡着的朋友叫醒！',
    [{ type: 'revive', value: 1, target: 'other' }], 'rare'),
  c('V05', '活力转移', 'vitality', 'coralPink',
    '将自己 1 点活力转移给一名玩家。', '牺牲自己，帮助朋友。',
    [{ type: 'heal', value: 1, target: 'other' }, { type: 'damage', value: 1, target: 'self' }]),
  c('V06', '爆发药剂', 'vitality', 'mistPurple',
    '本回合使用角色技能不消耗友情值。', '喝下去，技能随便用！',
    [{ type: 'modifyScene', target: 'self' }]),
  c('V07', '睡眠魔法', 'vitality', 'mistPurple',
    '一名玩家跳过下回合抽牌，但恢复 2 点活力。', '好好睡一觉，醒来更有精神。',
    [{ type: 'heal', value: 2, target: 'other' }]),
  c('V08', '心愿之力', 'vitality', 'starBlue',
    '消耗 2 点友情值，恢复 3 点活力。', '友情的力量可以治愈一切。',
    [{ type: 'heal', value: 3, target: 'self' }], 'rare'),

  // ==================== 奇遇牌 10 张 ====================
  c('A01', '星尘指南针', 'adventure', 'starBlue',
    '查看牌堆顶 3 张，选 1 张加入手牌，其余按任意顺序放回。', '指南针指引你找到想要的牌。',
    [{ type: 'draw', value: 1, target: 'self' }]),
  c('A02', '回声瓶', 'adventure', 'mistPurple',
    '复制上一张打出的行动牌的基础效果（目标可改变）。', '瓶中回荡着上一次行动的回声。',
    [{ type: 'copySkill', target: 'any' }], 'variable'),
  c('A03', '折叠地图', 'adventure', 'tideCyan',
    '将你的行动位置移动到序列中的任意位置。', '折叠地图，瞬间移动行动顺序。',
    [{ type: 'reorderTurn', target: 'self' }]),
  c('A04', '会唱歌的石子', 'adventure', 'honeyYellow',
    '全队各摸 1 张牌。', '石子唱起歌，大家都有收获。',
    [{ type: 'draw', value: 1, target: 'all' }]),
  c('A05', '倒流沙漏', 'adventure', 'mistPurple',
    '从弃牌堆取回 1 张牌加入手牌。', '时间倒流，用过的牌回来了。',
    [{ type: 'recycle', target: 'self' }]),
  c('A06', '云端滑梯', 'adventure', 'tideCyan',
    '从一名玩家手中随机抽 1 张牌，交给另一名玩家。', '顺着滑梯，牌滑到了别人手里。',
    [{ type: 'swapCard', target: 'any' }], 'variable'),
  c('A07', '月影布', 'adventure', 'mistPurple',
    '移除一名玩家的疲惫或沉默等负面状态。', '用月影布盖住坏状态。',
    [{ type: 'heal', value: 0, target: 'other' }]),
  c('A08', '秘密小路', 'adventure', 'mossGreen',
    '本回合跳过场景事件结算，但你不能获得友情奖励。', '走小路，避开场景的影响。',
    [{ type: 'modifyScene', target: 'self' }]),
  c('A09', '漂流瓶', 'adventure', 'tideCyan',
    '从弃牌堆选 1 张非奇遇牌加入手牌，随后弃 1 张牌。', '海里漂来一个瓶子，里面有惊喜。',
    [{ type: 'recycle', target: 'self' }, { type: 'discard', value: 1, target: 'self' }]),
  c('A10', '梦海望远镜', 'adventure', 'starBlue',
    '查看牌堆顶 6 张，选择最多 2 张展示给全队。', '用望远镜看看未来会摸到什么。',
    [{ type: 'peekHand', target: 'self' }]),

  // ==================== 道具牌 8 张（玩具暴走时增强+副作用） ====================
  c('T01', '糖果炮', 'item', 'coralPink',
    '对一名玩家造成 2 点伤害。玩具暴走时伤害 +1，但 25% 概率自己 -1 活力。', '威力巨大，但可能炸到自己。',
    [{ type: 'damage', value: 2, target: 'other' }], 'variable'),
  c('T02', '发条玩偶', 'item', 'honeyYellow',
    '获得 2 层护盾。玩具暴走时护盾 +1，但 25% 概率下回合行动延后。', '发条上紧，防御力拉满。',
    [{ type: 'shield', value: 2, target: 'self' }], 'variable'),
  c('T03', '魔法画笔', 'item', 'mistPurple',
    '复制一张手牌（获得其副本）。玩具暴走时复制 2 张，但 25% 概率随机弃 1 张。', '画什么有什么！',
    [{ type: 'draw', value: 1, target: 'self' }], 'variable'),
  c('T04', '星光棱镜', 'item', 'starBlue',
    '改变当前场景牌的效果（随机切换为另一张场景规则）。25% 概率场景对你不利。', '折射星光，改变场景规则。',
    [{ type: 'modifyScene', target: 'all' }], 'rare'),
  c('T05', '云朵降落伞', 'item', 'tideCyan',
    '免疫一次致命伤害（活力将归零时保留 1 点）。25% 概率弃 1 张牌。', '安全降落，不会摔晕。',
    [{ type: 'shield', value: 1, target: 'self' }], 'rare'),
  c('T06', '时光怀表', 'item', 'mistPurple',
    '本回合可额外执行一次主行动。25% 概率下回合不能行动。', '时间倒流，再行动一次！',
    [{ type: 'modifyScene', target: 'self' }], 'rare'),
  c('T07', '愿望放大镜', 'item', 'starBlue',
    '团队心愿进度 +1。25% 概率心愿进度 -1。', '放大愿望，但可能适得其反。',
    [{ type: 'modifyScene', target: 'all' }], 'rare'),
  c('T08', '友谊手环', 'item', 'coralPink',
    '与一名玩家 +2 友情。25% 概率反而 -1 友情。', '戴上手环，友情升温（或降温）。',
    [{ type: 'gainFriendship', value: 2, target: 'other' }], 'variable'),

  // ==================== 友情牌 8 张 ====================
  c('F01', '分享点心', 'friendship', 'honeyYellow',
    '给一名玩家 1 张手牌，双方各 +1 友情。', '分享美食，友情升温。',
    [{ type: 'gainFriendship', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'self' }]),
  c('F02', '击掌', 'friendship', 'coralPink',
    '与一名玩家击掌，双方各 +1 友情。', '简单的击掌，大大的温暖。',
    [{ type: 'gainFriendship', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'self' }]),
  c('F03', '拥抱', 'friendship', 'coralPink',
    '一名玩家恢复 1 点活力，双方各 +1 友情。', '一个拥抱，治愈一切。',
    [{ type: 'heal', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'other' }, { type: 'gainFriendship', value: 1, target: 'self' }]),
  c('F04', '约定', 'friendship', 'coralPink',
    '与一名玩家建立临时羁绊。', '拉钩上吊，一百年不许变。',
    [{ type: 'formBond', target: 'other' }]),
  c('F05', '和解', 'friendship', 'coralPink',
    '与一名玩家的友情差值缩小 2（向较高者靠拢），各摸 1 张牌。', '握手言和，重新做朋友。',
    [{ type: 'gainFriendship', value: 1, target: 'other' }, { type: 'draw', value: 1, target: 'self' }, { type: 'draw', value: 1, target: 'other' }]),
  c('F06', '友情爆发', 'friendship', 'coralPink',
    '消耗所有友情值，每点友情恢复 1 点活力。', '把友情全部转化为生命力！',
    [{ type: 'heal', value: 0, target: 'self' }], 'rare'),
  c('F07', '羁绊之力', 'friendship', 'starBlue',
    '若你有羁绊，你和所有羁绊对象各摸 1 张牌。', '羁绊的力量让大家一起成长。',
    [{ type: 'draw', value: 1, target: 'self' }]),
  c('F08', '心愿共鸣', 'friendship', 'starBlue',
    '全队各 +1 友情，团队心愿进度 +1。', '大家的心愿产生了共鸣！',
    [{ type: 'gainFriendship', value: 1, target: 'all' }, { type: 'modifyScene', target: 'all' }], 'rare'),
];

export const CARD_MAP: Record<string, Card> = Object.fromEntries(
  CARDS.map((card) => [card.id, card])
);

export function getCard(id: string): Card | undefined {
  return CARD_MAP[id];
}

// 按分类统计
export const CARD_COUNTS: Record<CardCategory, number> = CARDS.reduce(
  (acc, card) => {
    acc[card.category] = (acc[card.category] || 0) + 1;
    return acc;
  },
  {} as Record<CardCategory, number>
);
