import type { Character } from './types.js';

// ============================================================
// 12 名角色完整设计
// 一二、布布为绝对主角，其余 10 名为原创 Q 萌角色
// ============================================================

export const CHARACTERS: Character[] = [
  // ---------- 双主角 ----------
  {
    id: 'yier',
    name: '一二',
    title: '星轨小鹿',
    species: '星轨鹿',
    color: '#4A90D9',
    accentColor: '#E8F4FD',
    avatar: '/characters/yier.png',
    personality: '安静、敏锐、先观察后行动。嘴硬但会把最好的位置让给朋友。',
    background: '在"回声图书馆"长大，能听见道路记忆。为了寻找失散的北斗心愿碎片踏上旅程。',
    keywords: ['冷静', '细心', '勇敢', '善于分析', '提前准备'],
    playStyle: '信息型 / 规划型 — 查看手牌、预测场景、保护队友、改变行动顺序',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 6,
    isProtagonist: true,
    skill: {
      id: 'yier_insight',
      name: '星图校准',
      trigger: '每回合一次',
      timing: '你的回合内任意时刻',
      target: '任意一名玩家',
      effect: '查看目标的一张随机手牌，并可选择查看牌堆顶 1 张。若本轮有人被帮助，友情 +1。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '无手牌可查看时改为查看牌堆顶 2 张',
      code: 'yier_insight',
    },
  },
  {
    id: 'bubu',
    name: '布布',
    title: '蜜糖云兔',
    species: '云兔',
    color: '#F5A623',
    accentColor: '#FFF3E0',
    avatar: '/characters/bubu.png',
    personality: '热情、善于鼓励，紧张时会连续讲冷笑话。',
    background: '经营"临时糖果铺"，用甜味记住每个旅人的名字；她的云朵会收集大家的笑声。',
    keywords: ['温暖', '活泼', '想象力', '制造意外', '重视朋友'],
    playStyle: '支援型 / 反转型 — 送牌、承担负面、失败转机会、额外抽牌',
    baseVitality: 5,
    baseFriendship: 2,
    handLimit: 7,
    isProtagonist: true,
    skill: {
      id: 'bubu_burst',
      name: '甜甜转机',
      trigger: '消耗 1 点友情值',
      timing: '你的回合内或队友受到负面效果时',
      target: '一名队友',
      effect: '选择：①替队友承担下一次负面效果；②将一次失败效果转化为额外抽 1 张牌；③指定队友摸 2 张并选 1 张赠人。',
      cost: '1 点友情值',
      cooldown: '每回合一次',
      failure: '友情值不足时无法使用',
      code: 'bubu_burst',
    },
  },
  // ---------- 10 名原创配角 ----------
  {
    id: 'duoduo',
    name: '朵朵',
    title: '云朵邮差',
    species: '云朵精灵',
    color: '#87CEEB',
    accentColor: '#F0F8FF',
    avatar: '/characters/duoduo.png',
    personality: '温柔、可靠、守时，记得每个人的地址。',
    background: '在云朵邮局工作，送信时会偷偷在信封里塞一颗糖。',
    keywords: ['传递', '温柔', '守时'],
    playStyle: '资源传递型 — 送牌、获得友情、连接玩家',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 6,
    skill: {
      id: 'cloud_mail',
      name: '云朵速递',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '任意一名玩家',
      effect: '将一张手牌交给目标玩家，双方各获得 1 点友情值。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '无手牌时无法使用',
      code: 'cloud_mail',
    },
  },
  {
    id: 'tangtang',
    name: '糖糖',
    title: '糖果厨师',
    species: '糖果精灵',
    color: '#FF69B4',
    accentColor: '#FFF0F5',
    avatar: '/characters/tangtang.png',
    personality: '甜蜜、乐观、用美食治愈一切。',
    background: '在糖果城开了一家小甜品店，招牌菜是"心情马卡龙"。',
    keywords: ['治愈', '甜蜜', '补给'],
    playStyle: '恢复型 — 消耗手牌恢复活力、团队补给',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 6,
    skill: {
      id: 'candy_chef',
      name: '甜蜜补给',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '任意一名玩家',
      effect: '消耗一张手牌（材料），为目标恢复 1 点活力。若消耗的是友情牌，额外恢复 1 点。',
      cost: '弃置一张手牌',
      cooldown: '每回合一次',
      failure: '无手牌可消耗时无法使用',
      code: 'candy_chef',
    },
  },
  {
    id: 'asong',
    name: '阿松',
    title: '森林侦探',
    species: '松鼠侦探',
    color: '#228B22',
    accentColor: '#F0FFF0',
    avatar: '/characters/asong.png',
    personality: '锐利、专注、不放过任何细节，偶尔过度推理。',
    background: '在玩具森林开设侦探事务所，专门寻找丢失的玩具零件。',
    keywords: ['观察', '推理', '追踪'],
    playStyle: '信息型 — 查看最近用牌、追踪行动、识破身份',
    baseVitality: 4,
    baseFriendship: 1,
    handLimit: 6,
    skill: {
      id: 'forest_detective',
      name: '气味追踪',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '任意一名玩家',
      effect: '查看目标最近打出的一张牌（或最后获得的手牌），并可推测其身份倾向。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '目标无打牌记录时改为查看其一张手牌',
      code: 'forest_detective',
    },
  },
  {
    id: 'yueyue',
    name: '月月',
    title: '月光魔术师',
    species: '月光精灵',
    color: '#9370DB',
    accentColor: '#F5F0FF',
    avatar: '/characters/yueyue.png',
    personality: '神秘、优雅、说话带谜语，喜欢制造惊喜。',
    background: '在星光剧场表演魔术，最拿手的是"月光消失术"。',
    keywords: ['神秘', '幻术', '隐藏'],
    playStyle: '干扰型 — 隐藏行动、混淆信息、保护身份',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 6,
    skill: {
      id: 'moon_magician',
      name: '月影幻术',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '任意一名玩家（含自己）',
      effect: '让目标本轮的行动类型对其他玩家隐藏（日志显示为"神秘行动"）。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '无',
      code: 'moon_magician',
    },
  },
  {
    id: 'xiaoban',
    name: '小扳',
    title: '玩具修理师',
    species: '修理师精灵',
    color: '#FF8C00',
    accentColor: '#FFF8E7',
    avatar: '/characters/xiaoban.png',
    personality: '憨厚、认真、手巧，什么都能修。',
    background: '在玩具森林的修理铺工作，座右铭是"没有修不好的玩具"。',
    keywords: ['修理', '复活', '工具'],
    playStyle: '资源循环型 — 道具复活、废弃牌利用、持续作战',
    baseVitality: 5,
    baseFriendship: 1,
    handLimit: 5,
    skill: {
      id: 'toy_repair',
      name: '起死回生',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '弃牌堆中一张道具牌',
      effect: '从弃牌堆取回一张道具牌加入手牌。若弃牌堆无道具牌，改为抽 1 张牌。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '弃牌堆为空时改为抽 1 张',
      code: 'toy_repair',
    },
  },
  {
    id: 'mimi',
    name: '咪咪',
    title: '星星歌手',
    species: '星星精灵',
    color: '#FFD700',
    accentColor: '#FFFACD',
    avatar: '/characters/mimi.png',
    personality: '开朗、自信、用歌声鼓舞人心。',
    background: '星光剧场的头牌歌手，歌声能让星星亮起来。',
    keywords: ['歌唱', '鼓舞', '闪耀'],
    playStyle: '团队增益型 — 相邻玩家增益、友情提升、士气',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 6,
    skill: {
      id: 'star_singer',
      name: '星光二重奏',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '左右相邻两名玩家',
      effect: '让相邻两名玩家各获得 1 点友情值；若其中一人是一二或布布，额外恢复 1 点活力。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '相邻玩家不足时效果减半',
      code: 'star_singer',
    },
  },
  {
    id: 'qiaoqiao',
    name: '悄悄',
    title: '胆小幽灵',
    species: '幽灵',
    color: '#DDA0DD',
    accentColor: '#FAF0FF',
    avatar: '/characters/qiaoqiao.png',
    personality: '害羞、胆小、但关键时刻会鼓起勇气。',
    background: '住在月光湖底的小幽灵，害怕大声说话但喜欢偷听故事。',
    keywords: ['隐藏', '胆怯', '爆发'],
    playStyle: '防御反转型 — 首次负面免疫、隐藏状态、意外反击',
    baseVitality: 4,
    baseFriendship: 1,
    handLimit: 6,
    skill: {
      id: 'timid_ghost',
      name: '隐形',
      trigger: '被动 — 第一次受到负面效果时自动触发',
      timing: '受到负面效果时',
      target: '自己',
      effect: '第一次受到负面效果时免疫该效果，并摸 1 张牌。之后进入"勇敢"状态，下次攻击伤害 +1。',
      cost: '无（被动）',
      cooldown: '每局一次',
      failure: '已触发后本局不再生效',
      code: 'timid_ghost',
    },
  },
  {
    id: 'tuantuan',
    name: '团团',
    title: '淘气团子',
    species: '团子精灵',
    color: '#FFA500',
    accentColor: '#FFF5E6',
    avatar: '/characters/tuantuan.png',
    personality: '调皮、爱恶作剧、但心地善良。',
    background: '彩虹集市的小捣蛋鬼，喜欢偷换摊位上的东西。',
    keywords: ['捣蛋', '重定向', '意外'],
    playStyle: '干扰型 — 改变互动目标、制造混乱、反转局势',
    baseVitality: 5,
    baseFriendship: 1,
    handLimit: 5,
    skill: {
      id: 'naughty_dumpling',
      name: '偷天换日',
      trigger: '每回合一次',
      timing: '任意玩家打出互动牌时',
      target: '该互动牌的目标',
      effect: '将一张互动牌的目标重定向到另一名玩家。使用后直到你下回合，可再触发一次。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '无互动牌可重定向时不消耗',
      code: 'naughty_dumpling',
    },
  },
  {
    id: 'huahua',
    name: '画画',
    title: '梦境画师',
    species: '画师精灵',
    color: '#6A5ACD',
    accentColor: '#F0F0FF',
    avatar: '/characters/huahua.png',
    personality: '梦幻、陶醉、活在自己的色彩世界里。',
    background: '在纸片王国用画笔创造梦境，每一幅画都会变成真的。',
    keywords: ['创造', '转换', '色彩'],
    playStyle: '资源转换型 — 废弃牌转换类别、创造新牌、灵活应变',
    baseVitality: 4,
    baseFriendship: 2,
    handLimit: 7,
    skill: {
      id: 'dream_painter',
      name: '重绘梦境',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '弃牌堆中一张牌',
      effect: '将弃牌堆中一张牌转换为另一种类别（你选择）后加入手牌。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '弃牌堆为空时改为抽 1 张',
      code: 'dream_painter',
    },
  },
  {
    id: 'kaka',
    name: '咔咔',
    title: '发条骑士',
    species: '发条人偶',
    color: '#B87333',
    accentColor: '#FBF0E6',
    avatar: '/characters/kaka.png',
    personality: '坚定、勇敢、守承诺，上发条后会变得特别有力。',
    background: '梦境车站的守护者，用发条驱动身体，保护旅人的安全。',
    keywords: ['守护', '坚定', '牺牲'],
    playStyle: '坦克守护型 — 保护队友、承担伤害、延后行动',
    baseVitality: 6,
    baseFriendship: 1,
    handLimit: 5,
    skill: {
      id: 'windup_knight',
      name: '铁壁守护',
      trigger: '每回合一次',
      timing: '你的回合内',
      target: '任意一名玩家',
      effect: '为目标添加 2 层护盾，但你下一轮的行动顺序排到最后。',
      cost: '无',
      cooldown: '每回合一次',
      failure: '无',
      code: 'windup_knight',
    },
  },
];

export const CHARACTER_MAP: Record<string, Character> = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c])
);

export function getCharacter(id: string): Character | undefined {
  return CHARACTER_MAP[id];
}
